modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/duely/dwmh/issues" #optional
license="https://github.com/noobanidus/dwmh/blob/master/LICENSE"
[[mods]] #mandatory
modId="dwmh" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Dude! Where's my Horse?" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/dude-wheres-my-horse" #optional
credits="" #optional
authors="Noobanidus" #optional
description='''
'''
[[dependencies.dwmh]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dwmh]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
